TEST_RATIO: 0.2
MODEL_NAME: VGG16
FREEZE_ALL: True
FREEZE_TILL: None
IMAGE_SIZE: [224, 224, 3]  # as per VGG 16 model
INCLUDE_TOP: False
WEIGHTS: imagenet
NEURAL: 2
EPOCHS: 1
LOSS: CategoricalCrossentropy
OPTIMIZER: SGD
LEARNING_RATE: 0.01
AUGMENTATION: True
BATCH_SIZE: 128
