
artifacts_root: artifacts


data_ingestion:
  saved_images: artifacts/data_ingestion
  train_dir: artifacts/data_ingestion/train
  test_dir: artifacts/data_ingestion/test


prepare_base_model:
  root_dir_pre_model: artifacts/prepare_base_model
  updated_model: artifacts/prepare_base_model/base_model_updated.h5
  
prepare_callbacks:
  root_dir: artifacts/prepare_callbacks
  tensorboard_root_log_dir: artifacts/prepare_callbacks/tensorboard_log_dir
  checkpoint_model_filepath: artifacts/prepare_callbacks/checkpoint_dir/model.h5

training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5


Evaluation:
    training_data: artifacts\data_ingestion\saved_images
